application: roll-tech
version: 1
runtime: go
api_version: go1

beta_settings:
      cloud_sql_instances: roll-tech:us-central1:roll-tech-db

env_variables:
      CLOUDSQL_CONNECTION: cloudsql:roll-tech:us-central1:roll-tech-db*roll_tech_db/root/password

handlers:
- url: /.*
  script: _go_app
