application: roll-tech
version: 1
runtime: go
api_version: go1

beta_settings:
      cloud_sql_instances: roll-tech:us-central1:roll-tech-db

env_variables:
  MYSQL_CONNECTION: root@cloudsql(project-id:roll-tech-db)/roll_tech_db

handlers:
- url: /.*
  script: _go_app
